"""modify table posts

Revision ID: 09e550b2e0f9
Revises: ba942a0829e4
Create Date: 2017-07-16 15:19:58.586589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e550b2e0f9'
down_revision = 'ba942a0829e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.add_column('posts', sa.Column('read_count', sa.Integer(), nullable=True))
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'tags',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_index('ix_posts_update_timestamp', table_name='posts')
    op.drop_index('ix_roles_default', table_name='roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    op.create_index('ix_posts_update_timestamp', 'posts', ['update_timestamp'], unique=False)
    op.alter_column('posts', 'tags',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('posts', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('posts', 'read_count')
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
