"""empty message

Revision ID: 48b18ad6f4ca
Revises: dac343007c39
Create Date: 2017-09-14 14:22:27.757249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48b18ad6f4ca'
down_revision = 'dac343007c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_create_timestamp', table_name='comments')
    op.alter_column('comments', column_name='create_timestamp', new_column_name='create_datetime')
    op.create_index(op.f('ix_comments_create_datetime'), 'comments', ['create_datetime'], unique=False)
    op.alter_column('follows', column_name='create_timestamp', new_column_name='create_datetime')
    op.drop_index('ix_posts_create_timestamp', table_name='posts')
    op.alter_column('posts', column_name='create_timestamp', new_column_name='create_datetime')
    op.alter_column('posts', column_name='update_timestamp', new_column_name='update_datetime')
    op.create_index(op.f('ix_posts_create_datetime'), 'posts', ['create_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_create_datetime', table_name='posts')
    op.alter_column('posts', column_name='create_datetime', new_column_name='create_timestamp')
    op.alter_column('posts', column_name='update_datetime', new_column_name='update_timestamp')
    op.create_index(op.f('ix_posts_create_timestamp'), 'posts', ['create_timestamp'], unique=False)

    op.alter_column('follows', column_name='create_datetime', new_column_name='create_timestamp')

    op.drop_index('ix_comments_create_datetime', table_name='comments')
    op.alter_column('comments', column_name='create_datetime', new_column_name='create_timestamp')
    op.create_index(op.f('ix_comments_create_timestamp'), 'comments', ['create_timestamp'], unique=False)
    # ### end Alembic commands ###
