"""modify table comment

Revision ID: 574b02cf8992
Revises: 09e550b2e0f9
Create Date: 2017-07-27 16:55:46.671986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '574b02cf8992'
down_revision = '09e550b2e0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_timestamp', table_name='comments')
    op.alter_column('comments', column_name='timestamp', new_column_name='create_timestamp')
    op.create_index(op.f('ix_comments_create_timestamp'), 'comments', ['create_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_create_timestamp'), table_name='comments')
    op.alter_column('comments', column_name='create_timestamp', new_column_name='timestamp')
    op.create_index('ix_comments_timestamp', 'comments', ['timestamp'], unique=False)
    # ### end Alembic commands ###
