"""modify table follows

Revision ID: 5812b0fc9bcf
Revises: 574b02cf8992
Create Date: 2017-07-27 17:22:57.138143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5812b0fc9bcf'
down_revision = '574b02cf8992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', column_name='timestamp', new_column_name='create_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', column_name='create_timestamp', new_column_name='timestamp')
    # ### end Alembic commands ###
