"""empty message

Revision ID: 6b234c253972
Revises: a7a07efa5b85
Create Date: 2017-09-14 19:39:02.552501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b234c253972'
down_revision = 'a7a07efa5b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###
