"""empty message

Revision ID: 88238d50ac0e
Revises: 4878e2c4548c
Create Date: 2017-09-14 19:06:01.336196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88238d50ac0e'
down_revision = '4878e2c4548c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('register_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_date')
    # ### end Alembic commands ###
