"""modify table posts and add table category

Revision ID: a2e843ba57cb
Revises: 8a8cfa198bda
Create Date: 2017-03-13 23:09:07.184239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e843ba57cb'
down_revision = '8a8cfa198bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('update_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_update_timestamp'), 'posts', ['update_timestamp'], unique=False)
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_update_timestamp'), table_name='posts')
    op.drop_column('posts', 'update_timestamp')
    op.drop_column('posts', 'category_id')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
