"""modify table posts

Revision ID: fda17a93de46
Revises: a2e843ba57cb
Create Date: 2017-03-29 14:46:30.096430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda17a93de46'
down_revision = 'a2e843ba57cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body_html')
    op.add_column('posts', sa.Column('create_timestamp', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('tags', sa.String(length=200)))
    op.create_index(op.f('ix_posts_create_timestamp'), 'posts', ['create_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_create_timestamp'), table_name='posts')
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'create_timestamp')
    op.add_column('comments', sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
